# Generated by Django 5.0.1 on 2025-11-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('master_tailor', 'Master Tailor'), ('tailor', 'Tailor'), ('assistant_tailor', 'Assistant Tailor'), ('cutting_master', 'Cutting Master'), ('sewing_operator', 'Sewing Operator'), ('finishing', 'Finishing'), ('receptionist', 'Receptionist'), ('delivery_person', 'Delivery Person'), ('accountant', 'Accountant'), ('other', 'Other')], max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='orders.order')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='staff.staff')),
            ],
            options={
                'db_table': 'order_staff_assignments',
                'ordering': ['-assigned_date', '-id'],
                'unique_together': {('order', 'staff')},
            },
        ),
    ]
